---

- debug: { msg: "Running role:update.php for {{ wiki_id }}" }

- name: Set backup timestamp fact
  set_fact:
    backup_timestamp: "{{lookup('pipe','date +%Y%m%d%H%M%S')}}"

- name: Ensure backups directory exists for each wiki
  file:
    path: "{{ m_backups }}/{{ env }}/{{ wiki_id }}"
    state: directory
    mode: "{{ m_backups_mode }}"
    owner: "{{ m_backups_owner }}"
    group: "{{ m_backups_group }}"

#
# DUMP SQL from DB Master to backup-servers[0]
#
- name: "Backup wiki database prior to running update.php"
  include_role:
    name: remote-mysqldump
  vars:
    remote_server:            "{{ groups['db-master'][0] }}"

    # FIXME: these shouldn't be required
    # remote_server_ssh_user:   "{{ db_backup_server_remote_user }}"
    # remote_server_mysql_user: "{{  }}"
    # remote_server_mysql_pass: "{{  }}"
    dump_database:            "wiki_{{ wiki_id }}"
    target_server:            "{{ groups['backup-servers'][0] }}"

    # FIXME: this string below is copied from role:backup-db-wikis. It should
    #        be standardized somehow to avoid mistakes.
    target_server_path:       "{{ m_backups }}/{{ env }}/{{ wiki_id }}/{{ backup_timestamp }}_wiki.sql"
  run_once: true
  tags:
    - update.php
    - update.php-backup


- name: Run update.php on this wiki
  shell: >
    WIKI="{{ wiki_id }}" php "{{ m_mediawiki }}/maintenance/update.php" --quick
  # run_once see [1]
  run_once: true
  tags:
    - update.php
