---

- debug: { msg: "Running role:update.php for {{ wiki_id }}" }

- name: "Do backup of {{ wiki_id }}"
  include_role:
    name: backup-db-wikis
    tasks_from: do-wiki-backup
  vars:
    wiki_id: "{{ wiki_id }}"
  run_once: true
  tags:
    - sql-backup

- name: "Clean out all but the latest SQL backup file for {{ wiki_id }} IF DESIRED"
  include_role:
    name: sql-backup-cleanup
  vars:
    cleanup_wiki: "{{ wiki_id }}"
  run_once: true
  tags:
    - update.php
    - sql-backup-cleanup
  when: do_cleanup_sql_backup

- name: Run update.php on this wiki
  shell: >
    WIKI="{{ wiki_id }}" php "{{ m_mediawiki }}/maintenance/update.php" --quick
  # run_once see [1]
  run_once: true
  tags:
    - update.php
