---
- name: Install php dependency packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: "{{ package_php_apache_deps }}"

- name: Install PHP (RedHat/CentOS only)
  include: php-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Install PHP (Debian only)
  include: php-debian.yml
  when: ansible_os_family == "Debian"

- name: Install MS SQL driver for PHP
  include: mssql_driver_for_php.yml
  when: install_ms_sql_driver is defined and install_ms_sql_driver


- name: Write php.ini file
  template:
    src: php.ini.j2
    dest: "{{ m_php_ini }}"
  notify:
  - restart apache

- name: Write php.d ini files
  template:
    src: "{{ item }}.j2"
    dest: "/etc/php.d/{{ item }}"
  with_items:
  - 10-opcache.ini
  notify:
  - restart apache

- name: Write freetds.conf file
  template:
    src: freetds.conf.j2
    dest: /etc/freetds.conf
  notify:
  - restart apache

- name: Ensure PEAR Mail and Net_SMTP packages installed
  pear:
    name: "{{ item }}"
    state: latest
  tags:
  - latest
  with_items:
  - Mail
  - Net_SMTP
