---

# Package names
package_openssh_client: openssh-clients
package_cron: cronie
package_apache: httpd-devel
package_php_apache_deps:
  - zlib-devel
  - sqlite-devel
  - bzip2-devel
  - pcre-devel
  - openssl-devel
  - curl-devel
  - libxml2-devel
  - libXpm-devel
  - gmp-devel
  - libicu-devel
  - t1lib-devel
  - aspell-devel
  - libcurl-devel
  - libjpeg-devel
  - libvpx-devel
  - libpng-devel
  - freetype-devel
  - readline-devel
  - libtidy-devel
  - libmcrypt-devel
  - pam-devel
  - sendmail
  - sendmail-cf
  - m4
  - xz-libs
  - mariadb-libs


# Services
service_ntp: ntpd
service_apache: httpd


# Paths
path_custom_pem_ca_trust: "/etc/pki/ca-trust/source/anchors/"
path_custom_extended_ca_trust: "/etc/pki/ca-trust/source/"
path_apache_conf: /etc/httpd/conf/httpd.conf
path_apache_startup_config: "/etc/sysconfig/httpd"
path_apache_home: /usr/share/httpd
php_conf_d_path: "/etc/php.d/"
php_conf_d_files:
  - "10-opcache.ini"

# Commands
command_update_ca_trust: "update-ca-trust"
