---

- name: install lua packages
  yum:
    name: ['luajit', 'luajit-devel']
    state: present

- name: check out luasandbox from git
  git:
    repo=https://phabricator.wikimedia.org/diffusion/MLUS/php-luasandbox.git
    dest=/usr/src/luasandbox
    version=master

- name: compile and install luasandbox
  shell: phpize && ./configure --prefix=/usr/lib64/php && make all install
  args:
    chdir: /usr/src/luasandbox

- name: copy luasandbox initialization file
  copy:
    src=luasandbox.ini
    dest=/etc/php.d/luasandbox.ini
    mode=0600
    owner=root
