---
# Rsync pull role
#
# Inputs:
#   FIXME: Clean up docs below (remove WAS, add descriptions)
#   pulling_to_server:   server performing the rsync pull
#   pulling_to_path:
#   pulling_from_server:
#   pulling_from_path:
#   pulling_from_user:


#
# Put meza-ansible's private key on server within /root
#
- name: "Grant keys to rsync pulling-to server {{ pulling_to_server }}"
  copy:
    src: "{{ m_home }}/meza-ansible/.ssh/id_rsa"
    dest: /root/meza-ansible-id_rsa
    owner: root
    group: root
    mode: "0600"
  delegate_to: "{{ pulling_to_server }}"
  when:
    pulling_from_server != inventory_hostname
    # don't revoke keys if the backup server is the current server

# When the delegated server uses rsync to another server, allow it the same
# list of known hosts as the controller. In some cases this file may not exist,
# so ignore_errors.
# FIXME: Use this?
- name: "Copy known_hosts to delegated server {{ pulling_to_server }}"
  copy:
    src: "{{ m_home }}/meza-ansible/.ssh/known_hosts"
    dest: /root/meza-ansible-known_hosts
    owner: root
    group: root
    mode: "0644"
  delegate_to: "{{ pulling_to_server }}"
  ignore_errors: True
  when:
    pulling_from_server != inventory_hostname
    # don't revoke keys if the backup server is the current server

- name: Set rsync command fact for pulling-from server {{ pulling_from_server }} NOT pulling-to server
  set_fact:
    rsync_command: >
      rsync
      --delay-updates
      -F
      --compress
      --copy-links
      --archive
      --rsh="/usr/bin/ssh -S none -o StrictHostKeyChecking=no
      -l {{ pulling_from_user }} -i /root/meza-ansible-id_rsa
      -o UserKnownHostsFile=/root/meza-ansible-known_hosts"
      "{{ pulling_from_server }}:{{ pulling_from_path }}"
      "{{ pulling_to_path }}"
  when:
    pulling_to_server != pulling_from_server

- name: Set rsync command fact for pulling-from server IS {{ pulling_to_server }}
  set_fact:
    rsync_command: >
      rsync
      --delay-updates
      -F
      --compress
      --copy-links
      --archive
      "{{ pulling_from_path }}"
      "{{ pulling_to_path }}"
  when:
    pulling_to_server == pulling_from_server

- name: Run rsync
  shell: "{{ rsync_command }}"
  delegate_to: "{{ pulling_to_server }}"
  run_once: true

- name: "Revoke keys from pulling-to server {{ pulling_to_server }}"
  file:
    path: "/root/meza-ansible-id_rsa"
    state: absent
  delegate_to: "{{ pulling_to_server }}"
  when:
    pulling_from_server != inventory_hostname
    # don't revoke keys if the backup server is the current server
